### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by max1404** [denysvitali/sonos-web#12]
Hi @denysvitali,

on my server is an another service running on port 8888.
Need to change the port to 8010 in 3 files - nice would one file.

`sed -i 's/8888/8010/g' server.js src/js/main.js src/didl/radio.xml`

**Comment by denysvitali** [comment]
Hey @max1404,
the port must be changed in server.js and src/js/main.js.
The `src/didl/radio.xml` doesn't need the port to be changed since it was for debugging purpose.

I must find a clever way to set the port to be customized, I'll do it on the next release

**Comment by lcrossan** [comment]
Hey, I'd like to work on this. My thought was to use a JS file in `/config` that would export a port to use (8888 by default). Then anything that needed to use a port number could grab that export and use it from there. 

Sound good?

**Comment by denysvitali** [comment]
Hypothetically we can set the port in an external config.json file in the root directory, then read that file from server.js and serve the info when visiting `ip:port/config` since we need it in the client part to connect via websockets.
This will be tricky in a case, for example, when a reverse proxy is used.

**Comment by denysvitali** [comment]
Please, try to change the port in settings.json, and let me know if it works for you 👍   
If it doesn't work, feel free to open another issue. Have a wonderful day!
