### ISSUE TITLE
Run "npm start" as a service?

### ISSUE THREAD

**Issue by max1404** [denysvitali/sonos-web#13]
Can one "npm start" running as a service? If yes how? Does anyone have a built script?

**Comment by denysvitali** [comment]
If you want a fast and easy way you can execute `nohup npm start`, otherwise you may think to implement a systemd / service implementation.

You may take a look [here](http://superuser.com/questions/663989/how-to-create-a-custom-service-that-will-autostart-on-boot-on-archlinux#664790).
Where `ExecStart` will be something like `cd /home/dvitali/Documents/git/sonos-web/; npm start;`

**Comment by denysvitali** [comment]
I'm gonna close this since no answer was posted in 21 days. Feel free to comment if your issue isn't solved
