### ISSUE TITLE
Unable to seek SoundCloud and Youtube songs

### ISSUE THREAD

**Issue by denysvitali** [denysvitali/sonos-web#20]
As per title, with the current "proxing" system Sonos-Web is unable to seek a YouTube / Soundcloud track.

This may have something to do with the way it is streamed (maybe content-size?)

**Comment by Coriou** [comment]
I haven't tried Soundcloud and I don't know if the way their encode their songs is supported by Sonos. As per Youtube, I know it's possible by directly streaming the right file as described in #28

It doesn't work currently because the Youtube video is being transcoded live (from whatever we're getting from Youtube, to good ol' MP3) and we have no idea of the output file size until it's fully transcoded. There's no real workaround this (other than transcoding first, streaming second - but that'd mean you'd have to wait until the transcoding job is done before you can listen to your song which is not great user experience in most cases)
